Time::DATE_FORMATS[:default] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:datetime] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:date] = '%Y/%m/%d'
Time::DATE_FORMATS[:time] = '%H:%M:%S'
Time::DATE_FORMATS[:hhmm] = '%H:%M'
Date::DATE_FORMATS[:default] = '%Y/%m/%d'
Date::DATE_FORMATS[:month] = '%Y%m'
Date::DATE_FORMATS[:nosla] = '%Y%m%d'